### PR TITLE
Global variables (model-wise implicit linking)

### LINKED ISSUE #142: Implicitly link processes with "public" variables
#### TL;DR

Add a variable type `xsimlab.public` that allows for implicit process linking.

----

I am a relatively new user of this package. When I first started learning about it, I noticed that there was one aspect of `xsimlab` design that was unexpected:

```python
from another_class import AnotherClass

xsimlab.foreign(AnotherClass, 'my_var')
```

In other words, the user must **explicitly** link two processes. This approach has many benefits as explained in the docs. A major detriment to this approach, however, is significantly reduced modularity and reusability of the user-defined `process`es. For example, let's consider the minimal use case:

```python
@xs.process
class DefaultInput:
    some_input = xs.foreign(UseInput, 'some_input', intent='out')

    def initialize(self):
        self.some_input = 'foo'

@xs.process
class UseInput:
    some_input = xs.variable(intent='in')
```

Replacing the `DefaultInput` process with a `InputFromFile` process requires updates to every other linked process. In this simple case, we only need to do this for `UseInput`, but for larger connected networks of processes this is non-trivial.

My proposal (a mere point of discussion at this stage) is addition of a new `public` variable type:

```python
@xs.process
class DefaultInput:
    # Very similar to xs.foreign!
    some_input = xs.public('unique_name', intent='out')

    def initialize(self):
        self.some_input = 'foo'

@xs.process
class UseInput:
    some_input = xs.variable(name='unique_name', public=True, intent='in')
```

Replacing `DefaultInput` with `InputFromFile` is now trivial, even for large scale use cases. A `public` variable is processed at the model scope, so it can be read or provided by any other process in the model. The `group` variable type already behaves this way (if I'm reading the package code right), except that `intent='in'` is required for `group` variables only. A `group` variable would be a special case of `public` variable.

### PR DESCRIPTION
**Pull request by benbovy**
- [x] Closes #142
 - [x] Tests added
 - [x] Passes `black . && flake8`
 - [x] Fully documented, including `whats-new.rst` for all changes and `api.rst` for new API

### CODE REVIEW

**Comment by benbovy** [comment]
I'm struggling to find a good name for global references, which is currently `xs.global_ref()`. I wish I could use `xs.global()`, but `global` is a reserved keyword. Other candidates, although none of them really convince me:

- `xs.public()` -- I think that the concept here is much closer to local/global than private/public.
- `xs.anywhere()` -- too elusive

Any idea / opinion @eho-tacc?

**Comment by eho-tacc** [comment]
> Any idea / opinion @eho-tacc?

Ah, right. I suppose one could use an abbreviation like `xs.glob`, though this is still pretty elusive (and could be conflated with `glob.glob`). I'll keep thinking about this, but for now `global_ref` sounds best.

**Comment by benbovy** [comment]
> I suppose one could use an abbreviation like xs.glob, though this is still pretty elusive (and could be conflated with glob.glob)

Yeah I'd like to avoid abuse of wildcard characters in global names 😃 

Let's stick with `global_ref` for now.

**Comment by eho-tacc** [comment]
Thanks, @benbovy! Pretty busy this week, but I'll get around to testing this in my app ASAP

**Pull request merged**
